### ISSUE TITLE
switch camera multiple times cause a crash in Android 

### ISSUE THREAD

**Issue by MusabBasheer** [react-native-webrtc/react-native-webrtc#1016]
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int org.webrtc.CameraEnumerationAndroid$CaptureFormat.width' on a null object reference
       at org.webrtc.Camera2Session$CameraStateCallback.onOpened(Camera2Session.java:122)
       at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:148)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.os.HandlerThread.run(HandlerThread.java:67)

#### Expected behavior
should work without a crash. 
#### Observed behavior
When calling switch camera more than 3-4 times app crash
#### Steps to reproduce the problem
try to switch camera more than 3-4 times
#### Platform information

* **React Native version**:
64.2
* **Plugin version**:
 1.89.3
* **OS**: 
* Android 
* **OS version**:
 Android 11

**Comment by huseyindorudevtek** [comment]
is there any solution?

**Comment by leechanghoon3024** [comment]
same issue
i got error 
`java.lang.NullPointerException: 
  at org.webrtc.Camera2Session$CameraStateCallback.onOpened (Camera2Session.java:122)
  at android.hardware.camera2.impl.CameraDeviceImpl$1.run (CameraDeviceImpl.java:151)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.os.HandlerThread.run (HandlerThread.java:67)`

**Comment by MusabBasheer** [comment]
after upgrade package 
now app not crashed but camera stuck 

view these logs 
08-02 21:36:40.502 31331  9965 E org.webrtc.Logging: CameraCapturer: switchCamera: camera is not running.
08-02 21:36:40.502 31331  9965 E CameraCaptureController: Error switching camera: switchCamera: camera is not running.
