### ISSUE TITLE
App crashes after installing react-native-webrtc on  "react-native": "0.64.2"

### ISSUE THREAD

**Issue by mukash** [react-native-webrtc/react-native-webrtc#1026]
Please help, I install the app it installed successfully but when running it crashes instantly.

following are my dependencies

{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by 8BallBomBom** [comment]
Can you provide logs?
If you run Android Studio you should be able to grab the logcat output.
Or if the app is on the Google App Store then you might be able to grab a crash log/dump from the Play Console.

Without extra data it is hard to debug the issue.

**Comment by mukash** [comment]
Hello, Thank-you for the response

**Here is the log i got from Android Studio**

2021-06-18 11:16:09.645 19596-19596/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2021-06-18 11:16:09.647 19596-19596/? E/Zygote: accessInfo : 1
2021-06-18 11:16:09.701 19596-19596/? E/com.voip: Unknown bits set in runtime_flags: 0x8000
2021-06-18 11:16:10.532 19596-19668/com.voip E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.voip, PID: 19596
    java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.voip-B0kym6O-wpdNeEkj1TSx7w==/base.apk)
        at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
        at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
        at com.oney.WebRTCModule.WebRTCModule.initAsync(WebRTCModule.java:114)
        at com.oney.WebRTCModule.WebRTCModule.lambda$new$0$WebRTCModule(WebRTCModule.java:84)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$bDDwL4wYvjA9JkO_YVql2QzAUMI.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-06-18 11:16:11.376 19596-19596/com.voip E/ViewRootImpl: sendUserActionEvent() mView returned.
2021-06-18 11:16:12.213 19596-19596/com.voip E/unknown:ReactNative: Unable to launch logbox because react was unable to create the root view
2021-06-18 11:16:16.317 19596-19596/com.voip E/unknown:FabricViewStateManager: setState called without a StateWrapper

**Comment by 8BallBomBom** [comment]
What device are you using?

**Comment by mukash** [comment]
Samsung galaxy A20

**Comment by 8BallBomBom** [comment]
Alrighty, are you using proguard by any chance?
If so, add the following to your proguard-rules.pro file.

`-keep class org.webrtc.** { *; }`

**Comment by mukash** [comment]
i just created a fresh app, nothing is used just installed the library

**Comment by mukash** [comment]
ok i found proguard-rules.pro in android/app/proguard-rules.pro

should i the code you provided?
-keep class org.webrtc.** { *; }

**Comment by 8BallBomBom** [comment]
Yup, add it to the bottom of the file on a new line.

**Comment by 8BallBomBom** [comment]
What i'd also suggest is running `npm clean cache` and also `npm install` in the main directory of your project.
Just to ensure everything is clean and installed correctly.
Then run a new build.

**Comment by mukash** [comment]
okay

**Comment by mukash** [comment]
didn't worked still crashing
this is the progaurd-rules.pro file

# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:
-keep class org.webrtc.** { *; }

**Comment by mukash** [comment]
the recent log from android studio

`2021-06-18 11:46:44.921 28226-28226/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2021-06-18 11:46:44.922 28226-28226/? E/Zygote: accessInfo : 1
2021-06-18 11:46:44.968 28226-28226/? E/com.voip: Unknown bits set in runtime_flags: 0x8000
2021-06-18 11:46:46.043 28226-28303/com.voip E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.voip, PID: 28226
    java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.voip-WQn7qxaxPy9U7bo5XZrSwQ==/base.apk)
        at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
        at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
        at com.oney.WebRTCModule.WebRTCModule.initAsync(WebRTCModule.java:114)
        at com.oney.WebRTCModule.WebRTCModule.lambda$new$0$WebRTCModule(WebRTCModule.java:84)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$bDDwL4wYvjA9JkO_YVql2QzAUMI.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-06-18 11:46:47.237 28226-28226/com.voip E/unknown:ReactNative: Unable to launch logbox because react was unable to create the root view
2021-06-18 11:46:50.459 28226-28226/com.voip E/unknown:FabricViewStateManager: setState called without a StateWrapper`

**Comment by mukash** [comment]
Thanks for the support, Fixed it by changing 

  ```
 minSdkVersion = 21
   to
   minSdkVersion = 24
```

in android/build.gradle.

**Comment by 8BallBomBom** [comment]
Ahhhh, bit unusual, newer projects tend to have the minsdk higher.
Glad ya fixed it 👍🏻
