### ISSUE TITLE
Samsung Galaxy Note 10+ Apps Off Without Access to Camera

### ISSUE THREAD

**Issue by leechanghoon3024** [react-native-webrtc/react-native-webrtc#1044]
#### Expected behavior
App turns off when trying to connect rtc in Samsung Galaxy Note 10+ and get hardware information for the device
#### Observerd behavior
App turns off when trying to connect rtc in Samsung Galaxy Note 10+ and get hardware information for the device
Error logs obtained from the playstore
`java.lang.NullPointerException`
`java.lang.NullPointerException: 
  org.webrtc.Camera2Session$CameraStateCallback.onOpened(Camera2Session.java:122) 
  at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:151) 
  at android.os.Handler. handleCallback (Handler.java:938) 
  android.os.Handler.dispatchMessage (Handler.java:99)에서 
  android.os.Looper.loop (Looper.java:246)에서 
  android.os.HandlerThread.run에서 (HandlerThread.java :67)`

#### Steps to reproduce the problem
App turns off when trying to connect rtc in Samsung Galaxy Note 10+ and get hardware information for the device
#### Platform information

* **React Native version**: 0.64.0
* **Plugin version**: "^1.89.1"
* **OS**: Android 
* **OS version**: Android  11(SDK 30)

**Comment by saghul** [comment]
Can you paste the full adb logat?

**Comment by leechanghoon3024** [comment]
`2021-07-28 16:54:03.389 577-4902/? E/BufferQueueProducer: [StatusBar$_1506#0] disconnect: not connected (req=1)
2021-07-28 16:54:03.389 1506-2013/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:03.392 533-870/? E/Netd: getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2021-07-28 16:54:03.396 1011-12704/? E/Region: Region::unflatten() failed, invalid region
2021-07-28 16:54:03.411 1011-12704/? E/Region: Region::unflatten() failed, invalid region
2021-07-28 16:54:03.443 577-4902/? E/BufferQueueProducer: [NavigationBar0$_1506#0] disconnect: not connected (req=1)
2021-07-28 16:54:03.443 1506-2013/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:03.447 5183-5183/? E/unknown:FabricViewStateManager: setState called without a StateWrapper
2021-07-28 16:54:03.447 5183-5183/? E/unknown:FabricViewStateManager: setState called without a StateWrapper
2021-07-28 16:54:03.479 5183-5183/? E/unknown:FabricViewStateManager: setState called without a StateWrapper
2021-07-28 16:54:03.516 577-4902/? E/BufferQueueProducer: [StatusBar$_1506#0] disconnect: not connected (req=1)
2021-07-28 16:54:03.516 1506-2013/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:03.538 577-1072/? E/BufferQueueProducer: [NavigationBar0$_1506#0] disconnect: not connected (req=1)
2021-07-28 16:54:03.539 1506-2013/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:03.786 552-552/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(39)
2021-07-28 16:54:03.793 1011-1590/? E/SemContext.CaeProvider: setAttribute() : attribute is null!
2021-07-28 16:54:03.956 18348-18386/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/com.samsung.android.app.appsedge/shared_prefs/pref_recent.xml
2021-07-28 16:54:04.056 552-552/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(39)
2021-07-28 16:54:04.295 5183-6960/? E/org.webrtc.Logging: Camera2Session: Error: No supported capture formats.
2021-07-28 16:54:04.300 634-1445/? E/CameraService: setCompanionDisableSysFs : cc.disable property set to 0
2021-07-28 16:54:04.304 557-25702/? E/ExynosCamera: Build Date is (Oct 28 2020) (00:21:02)
2021-07-28 16:54:04.307 634-1445/? E/CameraService: onTorchStatusChangedLocked: cannot get torch status of camera 4: No such file or directory (-2)
2021-07-28 16:54:04.307 557-25702/? E/ExynosCameraInterface: INFO(HAL3_camera_device_initialize[392]): dual cam_state[0](3)
2021-07-28 16:54:04.307 634-1445/? E/Camera2-FrameProcessorBase: FrameProcessorBase: created
2021-07-28 16:54:04.307 634-1445/? E/Camera2-FrameProcessorBase: registerListener: Registering listener for frame id range 0 - 2147483647
// HERE 
2021-07-28 16:54:04.309 5183-6960/? E/AndroidRuntime: FATAL EXCEPTION: CaptureThread
    Process:com.myApp, PID: 5183
    java.lang.NullPointerException: Attempt to read from field 'int org.webrtc.CameraEnumerationAndroid$CaptureFormat.width' on a null object reference
        at org.webrtc.Camera2Session$CameraStateCallback.onOpened(Camera2Session.java:122)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-07-28 16:54:04.391 18348-18348/? E/CocktailBarContainerView: updateContainerVisibility: 0
2021-07-28 16:54:04.409 1011-1093/? E/system_server: Invalid ID 0x00000000.
2021-07-28 16:54:04.449 1909-1909/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2021-07-28 16:54:04.463 5183-5183/? E/unknown:ReactNative: Tried to remove non-existent frame callback
2021-07-28 16:54:04.474 577-620/? E/BufferQueueProducer: [com.myApp/com.myApp.MainActivity$_5183#0] disconnect: not connected (req=1)
2021-07-28 16:54:04.475 5183-6731/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:04.507 1011-1281/? E/SensorService: [EARPROXIMITY] getScreenRotation -  1627458844   507226 
2021-07-28 16:54:04.507 2606-2606/? E/pageboostd: Received HALT command code 2
2021-07-28 16:54:04.512 1011-1041/? E/SurfaceControl: [SEC_SF_EFFECTS] SurfaceControl.startSurfaceAnimation() sc=Surface(name=com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity$_1909)/@0x62e9e5f
2021-07-28 16:54:04.513 577-2550/? E/NativeSemDvfsGpuManager: acquire:: Start
2021-07-28 16:54:04.513 577-2550/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger 
2021-07-28 16:54:04.513 577-2550/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU() 
2021-07-28 16:54:04.513 577-2550/? E/NativeSemDvfsGpuManager: acquire:: End
2021-07-28 16:54:04.523 1909-1909/? E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2021-07-28 16:54:04.542 577-620/? E/BufferQueueProducer: [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity$_1909#0] disconnect: not connected (req=1)
2021-07-28 16:54:04.542 1909-12579/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:04.572 18348-18348/? E/CocktailBarContainerView: updateContainerVisibility: 0
2021-07-28 16:54:04.593 18348-18348/? E/DecorView: mWindow.mActivityCurrentConfig is null
2021-07-28 16:54:04.611 18348-18348/? E/DecorView: mWindow.mActivityCurrentConfig is null
2021-07-28 16:54:04.612 1011-1093/? E/DecorView: mWindow.mActivityCurrentConfig is null
2021-07-28 16:54:04.614 577-4902/? E/BufferQueueProducer: [com.samsung.android.app.cocktailbarservice/com.samsung.android.app.cocktailbarservice.CocktailBarService$_18348#0] disconnect: not connected (req=1)
2021-07-28 16:54:04.614 18348-18423/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:04.633 577-4902/? E/BufferQueueProducer: [com.samsung.android.app.cocktailbarservice/com.samsung.android.app.cocktailbarservice.CocktailBarService$_18348#0] disconnect: not connected (req=1)
2021-07-28 16:54:04.633 18348-18423/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:04.652 1506-1506/? E/WallpaperEventNotifier: registerCallback: Object tried to add another callback com.android.systemui.wallpaper.WallpaperUtils.registerSystemUIWidgetCallback:1237
2021-07-28 16:54:04.673 1506-1506/? E/SystemUIImageView: set Image Drawable!!
2021-07-28 16:54:04.695 577-577/? E/SurfaceFlinger: [Application Error: com.myApp#0] rejecting buffer: bufWidth=1456, bufHeight=1037, front.active_legacy.{w=1456, h=965}
2021-07-28 16:54:04.697 1011-1093/? E/DecorView: mWindow.mActivityCurrentConfig is null
2021-07-28 16:54:04.704 577-4902/? E/BufferQueueProducer: [Application Error: com.myApp#0] disconnect: not connected (req=1)
2021-07-28 16:54:04.704 1011-12341/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:04.728 577-620/? E/BufferQueueProducer: [StatusBar$_1506#0] disconnect: not connected (req=1)
2021-07-28 16:54:04.728 1506-2013/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:04.733 1011-1093/? E/DecorView: mWindow.mActivityCurrentConfig is null
2021-07-28 16:54:04.789 577-4902/? E/BufferQueueProducer: [NavigationBar0$_1506#0] disconnect: not connected (req=1)
2021-07-28 16:54:04.789 1506-2013/? E/OpenGLRenderer: ReliableSurface: perform returned an error
2021-07-28 16:54:04.912 1011-1466/? E/Pageboost: init for SI Policy is not done yet : global true sysint false
2021-07-28 16:54:04.918 2606-6981/? E/pageboostd: prefetch start : app comtowneerswww
2021-07-28 16:54:04.919 518-518/? E/audit: type=1400 audit(1627458844.913:422905): avc:  denied  { search } for  pid=2606 comm="pageboostd" name="com.google.android.gms" dev="sda34" ino=4712 scontext=u:r:pageboostd:s0 tcontext=u:object_r:privapp_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SM-N976N_10_0020 audit_filtered
2021-07-28 16:54:04.919 518-518/? E/audit: type=1300 audit(1627458844.913:422905): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=76530521f0 a2=0 a3=0 items=0 ppid=1 pid=2606 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="pageboostd" exe="/system/bin/pageboostd" subj=u:r:pageboostd:s0 key=(null)
2021-07-28 16:54:04.919 518-518/? E/audit: type=1327 audit(1627458844.913:422905): proctitle="/system/bin/pageboostd"
2021-07-28 16:54:04.919 518-518/? E/audit: type=1400 audit(1627458844.913:422906): avc:  denied  { search } for  pid=2606 comm="pageboostd" name="com.google.android.gms" dev="sda34" ino=4712 scontext=u:r:pageboostd:s0 tcontext=u:object_r:privapp_data_file:s0:c512,c768 tclass=dir permissive=0 SEPF_SM-N976N_10_0020 audit_filtered
2021-07-28 16:54:04.922 2606-6981/? E/pageboostd: comtowneerswww, amt 40771584 scnt 27 fcnt 18
2021-07-28 16:54:04.922 2606-6981/? E/pageboostd: prefetch end : app comtowneerswww data_amount 40771584
2021-07-28 16:54:05.311 18348-18386/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/com.samsung.android.app.appsedge/shared_prefs/pref_recent.xml
2021-07-28 16:54:05.513 577-2549/? E/NativeSemDvfsGpuManager: release:: Start
2021-07-28 16:54:05.513 577-2549/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU  , mTagName : SurfaceFlinger 
2021-07-28 16:54:05.514 577-2549/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU() 
2021-07-28 16:54:05.514 577-2549/? E/NativeSemDvfsGpuManager: release:: End
2021-07-28 16:54:05.864 1011-1098/? E/Watchdog: !@Sync 61358 [2021-07-28 16:54:05.864] FD count : 762, wdog_way : softdog`

@saghul 
The logcat immediately after the error occurred.
