### ISSUE TITLE
Problem with Promise.resolve in GetUserMediaImpl.java

### ISSUE THREAD

**Issue by Marinaarimany** [react-native-webrtc/react-native-webrtc#1054]
Hello, 
Currently I am working on a project which implements the Jitsi sdk (version 3.8.0). 
I have a problem when I am on a video call and I click on screen sharing, the application crashes and the logcat returns to me:

AndroidRuntime: FATAL EXCEPTION: main
    Process: name package, PID: 25268
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10751, result=-1, data=Intent { (has extras) }} to activity {name package.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
        at com.oney.WebRTCModule.GetUserMediaImpl.lambda$createScreenStream$1$GetUserMediaImpl(GetUserMediaImpl.java:301)
        at com.oney.WebRTCModule.-$$Lambda$GetUserMediaImpl$7c-RXkXhQAe0g-qWbo6i9uJK160.accept(Unknown Source:6)
        at com.oney.WebRTCModule.GetUserMediaImpl.createStream(GetUserMediaImpl.java:358)
        at com.oney.WebRTCModule.GetUserMediaImpl.createScreenStream(GetUserMediaImpl.java:289)
        at com.oney.WebRTCModule.GetUserMediaImpl.access$300(GetUserMediaImpl.java:32)
        at com.oney.WebRTCModule.GetUserMediaImpl$1.onActivityResult(GetUserMediaImpl.java:89)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:8413)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
2021-08-19 12:07:45.985 25268-25268/name package E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10751, result=-1, data=Intent { (has extras) }} to activity {name packagel/name package.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
        at com.oney.WebRTCModule.GetUserMediaImpl.lambda$createScreenStream$1$GetUserMediaImpl(GetUserMediaImpl.java:301)
        at com.oney.WebRTCModule.-$$Lambda$GetUserMediaImpl$7c-RXkXhQAe0g-qWbo6i9uJK160.accept(Unknown Source:6)
        at com.oney.WebRTCModule.GetUserMediaImpl.createStream(GetUserMediaImpl.java:358)
        at com.oney.WebRTCModule.GetUserMediaImpl.createScreenStream(GetUserMediaImpl.java:289)
        at com.oney.WebRTCModule.GetUserMediaImpl.access$300(GetUserMediaImpl.java:32)
        at com.oney.WebRTCModule.GetUserMediaImpl$1.onActivityResult(GetUserMediaImpl.java:89)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:8413)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8178) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
    
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10751, result=-1, data=Intent { (has extras) }} to activity {name package/name package.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
    	at com.oney.WebRTCModule.GetUserMediaImpl.lambda$createScreenStream$1$

Can you help me ? please 

Informations : 
React Native version : "react-native": "0.63.3", 
Plugin version : "react-native-webrtc": "^1.92.0",
OS : Android 
OS version : 10

Thank you

**Comment by saghul** [comment]
The Jitsi Meet SDK uses React Native 0.61.5, how come you are on 0.63 ?

**Comment by Marinaarimany** [comment]
I go through a react-native-jitsi library where I manually modified the sdk of jitsi

**Comment by saghul** [comment]
Sorry tthat package is not maintained by us, you'll have to ask the package author.

**Comment by Marinaarimany** [comment]
@saghul 
Thank you for your answer, I think the problem comes from webrtc but I will contact the developer of the package ^^
