### ISSUE TITLE
Crash when releasing the local stream on android

### ISSUE THREAD

**Issue by qusaieilouti99** [react-native-webrtc/react-native-webrtc#1257]
When releasing the local stream the app crashed on android and this is how we release the stream:
```
 releaseLocalStream = () => {
        if (this.localStream) {
            this.localStream.release(true);
            this.localStream = undefined;
        }
    }
```

the crash report:
```
FATAL EXCEPTION: pool-17-thread-1

java.util.ConcurrentModificationException

FATAL EXCEPTION: pool-17-thread-1
Process: com.pingme2022, PID: 20168
java.util.ConcurrentModificationException
	at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:734)
	at java.util.IdentityHashMap$ValueIterator.next(IdentityHashMap.java:832)
	at org.webrtc.VideoTrack.dispose(VideoTrack.java:59)
	at com.oney.WebRTCModule.GetUserMediaImpl$TrackPrivate.dispose(GetUserMediaImpl.java:496)
	at com.oney.WebRTCModule.GetUserMediaImpl.disposeTrack(GetUserMediaImpl.java:241)
	at com.oney.WebRTCModule.WebRTCModule.lambda$mediaStreamTrackRelease$16$com-oney-WebRTCModule-WebRTCModule(WebRTCModule.java:821)
	at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda16.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

Possible solution:
[Link](https://www.baeldung.com/java-concurrentmodificationexception) 

The line causing the issue is 59 in this file: [org.webrtc](https://chromium.googlesource.com/external/webrtc/+/master/sdk/android/api/org/webrtc/VideoTrack.java)

The issue happened to me only once while doing heavy testing on the video calls.

#### Expected Behavior
it shouldn't crash

#### Observed Behavior
it crashed

#### Steps to reproduce the issue
N/A

#### Platform Information

* **React Native Version**: 0.70.6
* **Plugin Version**: 106.0.1
* **OS**: Android 
* **OS Version**:  11

**Comment by saghul** [comment]
Can you consistently reproduce this?

I think I know what causes it, we need to run addSink / removeSink in the executor thread, since that's where we call dispose.

**Comment by qusaieilouti99** [comment]
It only happened twice and randomly when ending the call.
but I saw that in the call guide in our plugin you don't recommend releasing the local stream : [Destoying media stream](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/BasicUsage.md#destroying-the-media-stream)
but I saw it's outdated so is that correct what I'm doing to release the stream at the end of each call?

**Comment by saghul** [comment]
If you no longer need the stream is ok to release it.

**Comment by 8BallBomBom** [comment]
Will update the docs/handbook soon.
Not entirely sure why i didn't include the use of the release function.
Think it might have been due to the assumption that it was done automatically.

Will also run some tests on #1258 👍🏻
