### ISSUE TITLE
Updating from 1.100.1 to 106.0.1 version makes android app crash

### ISSUE THREAD

**Issue by fizawisedv** [react-native-webrtc/react-native-webrtc#1264]
My app works well with version [1.100.1](https://www.npmjs.com/package/react-native-webrtc/v/1.100.1). Updating to any versions above this is causing my app to crash on opening.

#### Expected Behavior
The app should not crash with versions above v1.100.1

#### Observed Behavior
After updating the version to 106.0.1 my app get crashed upon opening and I get the below error in android studio logcat:

```
W/ziparchive: Unable to open '/data/app/~~38hHIgiwraPxtzN4U0Yj_Q==/com.wisedv.bozu-JlOmatPphbUIFjizTL7IRA==/base.dm': No such file or directory
W/ziparchive: Unable to open '/data/app/~~38hHIgiwraPxtzN4U0Yj_Q==/com.wisedv.bozu-JlOmatPphbUIFjizTL7IRA==/base.dm': No such file or directory
W/com.wisedv.bozu: Zip open failed: Failure to verify dex file '/data/app/~~38hHIgiwraPxtzN4U0Yj_Q==/com.wisedv.bozu-JlOmatPphbUIFjizTL7IRA==/base.apk!classes4.dex': Method 6802(Lorg/webrtc/PeerConnectionFactory;.-$$Nest$smnativeCreatePeerConnectionFactory) has code, but is marked native or abstract
E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.wisedv.bozu.whateverString" on path: DexPathList[[zip file "/data/app/~~mT1H_juA9WOExIZFPizOUA==/com.wisedv.bozu-fOpidliK0Y4B0ckTwjBqMg==/base.apk"],nativeLibraryDirectories=[/data/app/~~mT1H_juA9WOExIZFPizOUA==/com.wisedv.bozu-fOpidliK0Y4B0ckTwjBqMg==/lib/arm64, /data/app/~~mT1H_juA9WOExIZFPizOUA==/com.wisedv.bozu-fOpidliK0Y4B0ckTwjBqMg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:289)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1064)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:1151)
        at android.app.LoadedApk.getResources(LoadedApk.java:1475)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:3264)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:3256)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7461)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8741)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

#Note: **multiDex** is enabled in my project.

#### Platform Information

* **React Native Version**: 0.63.4
* **Plugin Version**: 106.0.1
* **OS**: Android
* **OS Version**: 12

**Comment by saghul** [comment]
> java.lang.ClassNotFoundException: Didn't find class "com.wisedv.bozu.whateverString"

This plugin does not make use of this class. The bug seems to be elsewhere.

**Comment by fizawisedv** [comment]
Hi Saghul, thanks for responding! I am onto finding the source of the issue, I have one question.

Is there a possibility that there is some change in the package which requires extra config in my project to make things work? I have followed the installation steps specified [here](https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md). My app would work very well every time when I downgrade to v1.100.1; only going to v106.0.1 causes the issue.

**Comment by saghul** [comment]
We didn't change anything in that regard. Intentionally, that is.

**Comment by fizawisedv** [comment]
Updating the Gradle plugin fixed the issue. Thanks!
