### ISSUE TITLE
Local video stream doesn't continue when the app becomes foreground

### ISSUE THREAD

**Issue by araufdogan** [react-native-webrtc/react-native-webrtc#1314]
#### Expected Behavior
Local video stream should resume when app going foreground.

#### Observed Behavior
Local video stream doesn't resuming, keeps black screen. 

#### Steps to reproduce the issue
Click the home or back button, the app will go to the background. Wait 2-3 min and go back to the app. I don't want to start the camera in the foreground service (with permanent notification). I want to continue the stream when the app resumes.

I'm getting an error in the android studio,

```
Camera2Session: Error: Camera device could not be opened due to a device policy.
Session 0: Exception while stopping repeating: 
android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2350)
	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1277)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
	at org.webrtc.Camera2Session.stopInternal(Camera2Session.java:386)
	at org.webrtc.Camera2Session.reportError(Camera2Session.java:407)
	at org.webrtc.Camera2Session.access$600(Camera2Session.java:33)
	at org.webrtc.Camera2Session$CameraStateCallback.onError(Camera2Session.java:112)
	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1748)
	at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$QRhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
	at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

It's android security error. I tried to detect app state and when app state back to the active, I restarted the local stream. But It didn't fix the problem when there is peerconnection connected. I tried to remove old local stream and add new one to the peerconnection but It doesn't work.

#### Platform Information

* **React Native Version**: 0.70.3
* **Plugin Version**:  106.0.4
* **OS**: Android
* **OS Version**: 12 (It's not real device required)

**Comment by saghul** [comment]
You need to disable the track when the app goes into the background and re-enable it when it comes back. It's not automatic.

Setting track.enabled to false and then back to true will fix the problem.

**Comment by araufdogan** [comment]
It worked, thank you.
