### ISSUE TITLE
Android crashes with `NoSuchKeyException: dispatchEvent` on receiving remote track

### ISSUE THREAD

**Issue by streamer45** [react-native-webrtc/react-native-webrtc#1333]
#### Steps to reproduce the issue

It seems like receiving a remote track is sufficient to trigger this. Interestingly this is not happening on our debug builds but only when building for release.

I was able to track the error up to this line:

https://github.com/react-native-webrtc/react-native-webrtc/blob/51f0b09489fdf4fc70b9c812d58eb357869d7848/src/RTCPeerConnection.ts#L257

#### Platform Information

* **React Native Version**: 0.71.2
* **Plugin Version**: Tested both 106.0.4 and 106.0.6
* **OS**: Android 10

#### Logs

```
02-23 12:58:08.459 18369 18487 D InCallManager: requestAudioFocus(): res = AUDIOFOCUS_REQUEST_GRANTED
02-23 12:58:08.459 18369 18487 D InCallManager: startWiredHeadsetEvent()
02-23 12:58:08.460 18369 18487 D InCallManager: startNoisyAudioEvent()
02-23 12:58:08.462 18369 18487 D InCallManager: startMediaButtonEvent()
02-23 12:58:08.463 18369 18487 D InCallManager: startProximitySensor()
02-23 12:58:08.463 18369 18487 D InCallManager: setKeepScreenOn() true
02-23 12:58:08.463 18369 18369 D AppRTCProximitySensor: start@[name=main, id=2]
02-23 12:58:08.463 18369 18369 D AppRTCProximitySensor: Proximity sensor: name=stk3x3x alsprx, vendor: Sensortek, power: 0.1, resolution: 0.05000305, max range: 5.000305, min delay: 0, type: android.sensor.proximity, max delay: 65535000, reporting mode: 1, isWakeUpSensor: true
02-23 12:58:08.464  1961  2386 I AS.AudioService: setMode(mode = 3, callingPackage = com.mattermost.rnbeta, Process ID: 18369
02-23 12:58:08.464  1961  1985 I SensorService: check list, getPackageName  com.zxcpoiu.incallmanager.AppRTC.AppRTCProximitySensor
02-23 12:58:08.464   700 20797 D audio_hw_primary: adev_set_mode: mode 3
02-23 12:58:08.464   749 30066 D AudioPolicyManagerCustom: setPhoneState() state 3
02-23 12:58:08.468 18369 18369 D AppRTCBluetoothManager: start
02-23 12:58:08.469   749 30066 D APM_AudioPolicyManager: getNewOutputDevices selected devices {type:0x2,@:}
02-23 12:58:08.470 18369 18369 I AudioManager: In isBluetoothScoAvailableOffCall(), calling appilication: com.mattermost.rnbeta, return value: true
02-23 12:58:08.472 18369 18369 D AppRTCBluetoothManager: BluetoothAdapter: enabled=false, state=OFF, name=Redmi Note 7, address=02:00:00:00:00:00
02-23 12:58:08.473 18369 18369 D BluetoothHeadset: Binding service...
02-23 12:58:08.474   700 20797 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
02-23 12:58:08.475  1961  3510 W BluetoothManagerService: bindBluetoothProfileService:Trying to bind to profile: 1, while Bluetooth is disabled
02-23 12:58:08.477 18369 18369 D AppRTCBluetoothManager: HEADSET profile state: DISCONNECTED
02-23 12:58:08.477 18369 18369 D AppRTCBluetoothManager: Bluetooth proxy for headset profile has started
02-23 12:58:08.477 18369 18369 D AppRTCBluetoothManager: start done: BT state=HEADSET_UNAVAILABLE
02-23 12:58:08.478   700 20797 D audio_hw_extn: audio_extn_fm_set_parameters: Enter
02-23 12:58:08.478   700 20797 D audio_hw_hfp: hfp_set_parameters: enter
02-23 12:58:08.479   749 30066 V AudioPolicyManagerCustom: checkAndSetVolume() cannot set stream 3 volume with force use = 1 for comm
02-23 12:58:08.480   749 30066 D APM_AudioPolicyManager: getNewOutputDevices selected devices AUDIO_DEVICE_NONE
02-23 12:58:08.480   749 30066 I chatty  : uid=1041(audioserver) Binder:749_B identical 1 line
02-23 12:58:08.481   749 30066 D APM_AudioPolicyManager: getNewOutputDevices selected devices AUDIO_DEVICE_NONE
02-23 12:58:08.481   749 30066 V AudioPolicyManagerCustom: setPhoneState() in call state management: new state is 3
02-23 12:58:08.481   749 30066 V AudioFlinger: invalidateStream() stream 10
02-23 12:58:08.498  2202  2689 I vol.VolumeDialogControl: updateStreamLevelW stream:8 ss.level:14 level:15 ss.levelMax:15 mute:true
02-23 12:58:08.499  2202  2689 I vol.VolumeDialogControl: updateStreamLevelW stream:8 ss.level:15 level:8 ss.levelMax:15 mute:true
02-23 12:58:08.500  2202  2689 I vol.VolumeDialogControl: updateStreamLevelW stream:8 ss.level:8 level:4 ss.levelMax:15 mute:true
02-23 12:58:08.501  2202  2689 I vol.VolumeDialogControl: updateStreamLevelW stream:10 ss.level:15 level:12 ss.levelMax:15 mute:false
02-23 12:58:08.502  2202  2689 I vol.VolumeDialogControl: updateStreamLevelW stream:10 ss.level:12 level:2 ss.levelMax:15 mute:false
02-23 12:58:08.502  2202  2689 I vol.VolumeDialogControl: updateStreamLevelW stream:10 ss.level:2 level:9 ss.levelMax:15 mute:false
02-23 12:58:08.504  2202  2689 I vol.VolumeDialogControl: updateStreamLevelW stream:10 ss.level:9 level:15 ss.levelMax:15 mute:false
02-23 12:58:08.509   749 22804 D AudioPolicyManagerCustom: setForceUse() usage 7, config 0, mPhoneState 3
02-23 12:58:08.509  1961  2386 I AS.AudioService: In setMode(), calling disconnectBluetoothSco()
02-23 12:58:08.509  1961  2117 I AS.BtHelper: In disconnectBluetoothSco(), exceptPid: 18369
02-23 12:58:08.510  1961  2117 I AS.BtHelper: In checkScoAudioState(), mScoAudioState: 0
02-23 12:58:08.510 18369 18487 I AudioManager: In isSpeakerphoneOn(), calling application: com.mattermost.rnbeta
02-23 12:58:08.510  1961  2386 I AS.AudioDeviceBroker: In isSpeakerphoneOn(), mForcedUseForCommExt: 1
02-23 12:58:08.510   700 20797 W DeviceHAL: Error from HAL Device in function get_mic_mute: Function not implemented
02-23 12:58:08.510   700 20797 W DeviceHAL: Error from HAL Device in function get_mic_mute: Function not implemented
02-23 12:58:08.513 18369 18369 D InCallManager: --- updateAudioDeviceState: wired headset=false, BT state=HEADSET_UNAVAILABLE
02-23 12:58:08.513 18369 18369 D InCallManager: Device status: available=[], selected=NONE, user selected=NONE
02-23 12:58:08.513 18369 18369 D InCallManager: setAudioDeviceInternal(device=SPEAKER_PHONE)
02-23 12:58:08.514 18369 18369 I AudioManager: In isSpeakerphoneOn(), calling application: com.mattermost.rnbeta
02-23 12:58:08.514  1961  2386 I AS.AudioDeviceBroker: In isSpeakerphoneOn(), mForcedUseForCommExt: 1
02-23 12:58:08.514 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 ctor +0ms
02-23 12:58:08.514 18369 18369 D InCallManager: New device status: available=[SPEAKER_PHONE, EARPIECE], selected=SPEAKER_PHONE
02-23 12:58:08.514 18369 18369 D InCallManager: --- updateAudioDeviceState done
02-23 12:58:08.518 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 createOffer +16ms
02-23 12:58:08.523 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 createOffer OK +43ms
02-23 12:58:08.523 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 setLocalDescription +1ms
02-23 12:58:08.526 18369 18475 I org.webrtc.Logging: NetworkMonitor: Start monitoring with native observer 512186567008 fieldTrialsString: 
02-23 12:58:08.533 18369 18475 W org.webrtc.Logging: NetworkMonitorAutoDetect: Unable to obtain permission to request a cellular network.
02-23 12:58:08.536 18369 18462 I org.webrtc.Logging: NetworkMonitorAutoDetect: Network becomes available: 100
02-23 12:58:08.538 18369 18462 I org.webrtc.Logging: NetworkMonitorAutoDetect: capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -52]
02-23 12:58:08.539 18369 18477 D com.oney.WebRTCModule.WebRTCModule: onIceGatheringChangeGATHERING
02-23 12:58:08.540 18369 18462 I org.webrtc.Logging: NetworkMonitorAutoDetect: link properties changed
02-23 12:58:08.548 18369 18477 D com.oney.WebRTCModule.WebRTCModule: onIceCandidate
02-23 12:58:08.548 18369 18477 D com.oney.WebRTCModule.WebRTCModule: onIceCandidate
02-23 12:58:08.555 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 setLocalDescription OK +18ms
02-23 12:58:08.555 18369 18487 D TurboLogger: local offer, sending: {"sdp":"v=0\r\no=- 742380421333402725 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:jnUq\r\na=ice-pwd:lFY+9+uOZSICi99RYE8N4/7z\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 22:0F:66:FF:9E:17:1A:CC:8A:89:56:11:55:F4:20:03:49:CC:64:AD:A6:E7:DE:91:B5:E8:11:83:AA:B8:90:CD\r\na=setup:actpass\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n","type":"offer"}
02-23 12:58:08.651 18369 18477 D com.oney.WebRTCModule.WebRTCModule: onIceGatheringChangeCOMPLETE
02-23 12:58:08.666 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 setRemoteDescription +124ms
02-23 12:58:08.669 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 addIceCandidate +1ms
02-23 12:58:08.675 18369 18487 I chatty  : uid=10290(com.mattermost.rnbeta) mqt_native_modu identical 2 lines
02-23 12:58:08.678 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 addIceCandidate +1ms
02-23 12:58:08.680 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 addIceCandidate +2ms
02-23 12:58:08.682 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 setRemoteDescription +2ms
02-23 12:58:08.684 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +3ms
02-23 12:58:08.690 18369 18477 D com.oney.WebRTCModule.WebRTCModule: onAddTrack
02-23 12:58:08.699 18369 18487 I TurboLogger: rn-webrtc:pc:DEBUG 0 ontrack +23ms
02-23 12:58:08.705 18369 18487 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
02-23 12:58:08.705 18369 18487 E AndroidRuntime: Process: com.mattermost.rnbeta, PID: 18369
02-23 12:58:08.705 18369 18487 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: dispatchEvent
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:110)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:114)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:146)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.mattermostreactnativeturbolog.Helpers.convertMapToJson(Helpers.java:21)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.mattermostreactnativeturbolog.ReactNativeTurboLogModuleImpl.format(ReactNativeTurboLogModuleImpl.java:188)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.mattermostreactnativeturbolog.ReactNativeTurboLogModuleImpl.write(ReactNativeTurboLogModuleImpl.java:111)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.mattermostreactnativeturbolog.ReactNativeTurboLogModule.write(ReactNativeTurboLogModule.java:33)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
02-23 12:58:08.705 18369 18487 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
02-23 12:58:08.708  1961  1985 W ActivityTaskManager:   Force finishing activity com.mattermost.rnbeta/.MainActivity
```

**Comment by streamer45** [comment]
Update: the error is super confusing but it seems like the crash happens when trying to log stuff out of the `RTCTrackEvent` (e.g. `ev.track`). Not sure why it would fail so dramatically but I guess it's trying to convert some objects internally and failing to do so.

Closing this as there's not much to do on this side I feel.

**Comment by 8BallBomBom** [comment]
Thanks for the report 👍🏻 
Definitely not ideal though 🤔
