### ISSUE TITLE
Android crashing in android version 11.  keyword: createEgl14  EglBase

### ISSUE THREAD

**Issue by Timson020** [react-native-webrtc/react-native-webrtc#1335]
#### Expected Behavior

start app

#### Observed Behavior
crashing in start app

#### Steps to reproduce the issue
 - npx react-native init RNDemo
 - npm install react-native-webrtc -S
 - create release keystore ```keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000```
 - step release info in android file
 - in android folder run ``` ./gradlew assembleRelease ```
 - adb install ./android/.../.../../../release.apk
 - start app on my phone

#### Error msg
```
java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/~~5vie0WnZF1Bdt381p0efGg==/com.rndemo-TDEq7tPDZiyPY074cMTZng==/base.apk)
                                                                                                    	at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
                                                                                                    	at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:115)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:81)
                                                                                                    	at com.oney.WebRTCModule.WebRTCModulePackage.createNativeModules(WebRTCModulePackage.java:14)
                                                                                                    	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
                                                                                                    	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
                                                                                                    	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1456)
                                                                                                    	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1427)
                                                                                                    	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1338)
                                                                                                    	at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:135)
                                                                                                    	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1109)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
```

#### Platform Information

* **React Native Version**: 0.71.3
* **Plugin Version**: 106.0.6
* **OS**: Android 
* **OS Version**: android 11

**Comment by saghul** [comment]
Have you enabled desuraging? (Check the android doc in the Documentation folder)

**Comment by Timson020** [comment]
i change android/build.gradle like it, rebuild not crash && not logcat error

```gradle
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        // minSdkVersion = 21
        // change here
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}
```

**Comment by saghul** [comment]
Setting minSdk to 24 is another way around, but not everyone can do that :-)

**Comment by Timson020** [comment]
@saghul 
i don't know enabled desuraging,
how can i find it ?
i just 
- ```npx react-native init RNDemo```
- ``` npm i react-native-webrtc -S ```
- build release apk, then app crash on start

**Comment by saghul** [comment]
Check here: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md

**Comment by ufukomer** [comment]
setting minsdk to 24 solved the issue:

```gradle
// build.gradle

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24 // set to 24
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

```
