### ISSUE TITLE
Android:  App Example crashing on android X

### ISSUE THREAD

**Issue by iita71737** [react-native-webrtc/react-native-webrtc#1336]
I clone this library and test this example,
but Crash promptly when Android Studio bundle to physical mobile .

#### Platform Information
```
{
  "name": "GumTestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "install-local ../../"
  },
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.5",
    "react-native-webrtc": "*"
  },
  "devDependencies": {
    "@babel/core": "7.12.3",
    "@babel/runtime": "7.12.5",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.5.1",
    "eslint": "6.8.0",
    "install-local": "^3.0.1",
    "jest": "25.5.4",
    "metro-react-native-babel-preset": "0.59.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

```
Gradle JDK 14

Android Gradle Plugin Version 4.1.0
Gradle Version 7.1
```

* **OS**: 
Android X 
Sony G8441

* **OS Version**: 
Android Version 9

**Comment by saghul** [comment]
Please paste the crash logs.

**Comment by iita71737** [comment]
`---------------------------- PROCESS STARTED (25784) for package com.gumtestapp ----------------------------
2023-03-10 14:28:47.521 25784-25784 com.gumtestapp          com.gumtestapp                       W  Failure to verify dex file '/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk': Method 36566(Lorg/webrtc/PeerConnectionFactory;.-$$Nest$smnativeCreatePeerConnectionFactory) has code, but is marked native or abstract
2023-03-10 14:28:47.526 25784-25784 LoadedApk               com.gumtestapp                       E  Unable to instantiate appComponentFactory
                                                                                                    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/lib/arm64, /data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.LoadedApk.createAppFactory(LoadedApk.java:231)
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:736)
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:815)
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1037)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5773)
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:205)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:280)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6706)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk because: Failure to verify dex file '/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk': Method 36566(Lorg/webrtc/PeerConnectionFactory;.-$$Nest$smnativeCreatePeerConnectionFactory) has code, but is marked native or abstract
                                                                                                    		at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                                    		at dalvik.system.DexFile.openDexFile(DexFile.java:354)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:101)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:75)
                                                                                                    		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
                                                                                                    		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
                                                                                                    		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                                                                                                    		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
                                                                                                    		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:732)
                                                                                                    		... 12 more
2023-03-10 14:28:47.536 25784-25784 Perf                    com.gumtestapp                       I  Connecting to perf service.
2023-03-10 14:28:47.544 25784-25784 AndroidRuntime          com.gumtestapp                       D  Shutting down VM
2023-03-10 14:28:47.547 25784-25784 AndroidRuntime          com.gumtestapp                       E  FATAL EXCEPTION: main
                                                                                                    Process: com.gumtestapp, PID: 25784
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.gumtestapp.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.gumtestapp.MainApplication" on path: DexPathList[[zip file "/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/lib/arm64, /data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1074)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5870)
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:205)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:280)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6706)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.gumtestapp.MainApplication" on path: DexPathList[[zip file "/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/lib/arm64, /data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1066)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5870) 
                                                                                                    	at android.app.ActivityThread.access$1100(ActivityThread.java:205) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:280) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6706) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
                                                                                                    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk because: Failure to verify dex file '/data/app/com.gumtestapp-6EPkNlHjDXzZTYeJIEHzLg==/base.apk': Method 36566(Lorg/webrtc/PeerConnectionFactory;.-$$Nest$smnativeCreatePeerConnectionFactory) has code, but is marked native or abstract
                                                                                                    		at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                                    		at dalvik.system.DexFile.openDexFile(DexFile.java:354)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:101)
                                                                                                    		at dalvik.system.DexFile.<init>(DexFile.java:75)
                                                                                                    		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
                                                                                                    		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
                                                                                                    		at dalvik.system.DexPathList.<init>(DexPathList.java:164)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
                                                                                                    		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
                                                                                                    		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
                                                                                                    		at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
                                                                                                    		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
                                                                                                    		at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:732)
                                                                                                    		at android.app.LoadedApk.getClassLoader(LoadedApk.java:815)
                                                                                                    		at android.app.LoadedApk.getResources(LoadedApk.java:1037)
                                                                                                    		at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
                                                                                                    		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5773)
                                                                                                    		... 8 more
2023-03-10 14:28:47.556 25784-25784 Process                 com.gumtestapp                       I  Sending signal. PID: 25784 SIG: 9
---------------------------- PROCESS ENDED (25784) for package com.gumtestapp ----------------------------
`

**Comment by iita71737** [comment]
I'm not sure above this is enough,
but I run app on Android Studio,
and build success.

`03/10 14:31:22: Launching 'app' on Sony G8441.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.gumtestapp/com.gumtestapp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER`

and physical mobile auto open the demo app,
then, crash down.

no see any thing what happened or error message in ReactNative app

**Comment by saghul** [comment]
> Didn't find class "com.gumtestapp.MainApplication" on path: DexPathList[

Something is very messes up with that build.

**Comment by davidliu** [comment]
Hmm, repros for me. I'll take a look at updating the build here since it's pretty old.
