### ISSUE TITLE
Rename package to alt.webrtc cause crash

### ISSUE THREAD

**Issue by thanhlieng** [react-native-webrtc/react-native-webrtc#1355]
I wanna use react-native-webrtc along with another package that already contain org.webrtc so i have to rename to alt.webrtc.
Build android was success but the app crash right after react-native bundling 100% and i have receive this error: 
No implementation found for void alt.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_alt_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_alt_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)

Im not sure why this error cause.

E/m.call_next_ge: No implementation found for void alt.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_alt_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_alt_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.call_next_gen, PID: 7518
    java.lang.UnsatisfiedLinkError: No implementation found for void alt.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_alt_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_alt_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
        at alt.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
        at alt.webrtc.PeerConnectionFactory.initialize(PeerConnectionFactory.java:295)
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:104)
        at com.oney.WebRTCModule.WebRTCModule.<init>(WebRTCModule.java:81)
        at com.oney.WebRTCModule.WebRTCModulePackage.createNativeModules(WebRTCModulePackage.java:14)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1456)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1427)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1338)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:135)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1109)
        at java.lang.Thread.run(Thread.java:923)

I can't rename that another package

* ** "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.14.5",
    "jssip": "^3.10.0",
    "patch-package": "^6.5.1",
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-jssip": "^3.7.6",
    "react-native-permissions": "^3.7.3",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-webrtc": "^106.0.7",
    "stringee-react-native": "1.3.15"**: 
* **OS**: Android 13.0

**Comment by thanhlieng** [comment]
> 
Thanks for ur reply
Yes, i can excluding one of the webrtc dependencies in gradle. But the problem is that other package (stringee-react-native) is using old version of webrtc and I'm trying to use jssip to make phone call that seem only work with new version of react-native-webrtc (-v 106), and if i excluding webrtc from stringee, stringee won't work. i need both to work
