### ISSUE TITLE
Android: incorrect detecting optimal camera resolution OR GL problems

### ISSUE THREAD

**Issue by mastersam92** [react-native-webrtc/react-native-webrtc#1361]
Sometimes needed to stream with as much camera resolution as it can provide - no big FPS needed
So, I just setting obviously too big camera resolution so any device provide as much resolution as it can( code below )
Some devices work perfectly, but others - even local preview isn't working, just black screen

An error happens on every frame 

Also I started investigate frame processor( for test it simplest - just Log frame resolution ) so have some extra data

_( resolution settings )_
```
mediaDevices
      .getUserMedia({
        audio: true,
        video: {
          width: 10000,
          height: 10000,
          facingMode: 'environment',
        },
      })
```

_( CustomFrameProcessor )_
```
public class CustomVideoFrameProcessor implements VideoFrameProcessor {
    private static final String TAG = "CustomVideoFrameProcessor";

    @Override
    public VideoFrame process(VideoFrame frame, SurfaceTextureHelper textureHelper) {
        Log.d(
            TAG,
            String.format("On Proccess frame width: %d, height: %d", frame.getBuffer().getWidth(),  frame.getBuffer().getHeight())
        );
        frame.retain();
        return frame;
    }
}
```

_( Logcat messages on every frame )_
```
D/CustomVideoFrameProcessor: On Proccess frame width: 4160, height: 3120
E/IMGSRV: :0: IsTextureConsistent: IMGEGLImage is not consistent
E/GLConsumer: [SurfaceTexture-1-14119-0] bindTextureImage: error binding external image: 0x502
E/surfaceTexture: Exception updateTexImage
    java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:249)
        at org.webrtc.SurfaceTextureHelper.updateTexImage(SurfaceTextureHelper.java:334)
        at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:354)
        at org.webrtc.SurfaceTextureHelper.lambda$returnTextureFrame$5$org-webrtc-SurfaceTextureHelper(SurfaceTextureHelper.java:295)
        at org.webrtc.SurfaceTextureHelper$$ExternalSyntheticLambda6.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

As we can see, frame resolution is 4160 x 3120, but device documentation told as it support 1920 x 1080, 30 FPS( and it work on 1920 x 1080 )
But many other devices, with much good camera( 48-64-etc Mp ) work good with even more resolution ( 4640 x 3472 as example )

Seems like, there are some problems with auto-setting optimal camera params
Or, as some similar errors get caught on other projects, it may be some hardware or GL restrictions  

#### Expected Behavior

No error

#### Observed Behavior

Error on every frame. Even local preview isn't work 

#### Steps to reproduce the issue

Set obviously big resolution to allow devices provide as big resolution as it can

#### Platform Information

* **React Native Version**: 71
* **Plugin Version**: 106.0.7
* **OS**: Android 9.0 + MIUI ( Huawei )
* **Device**: JAT-LX1 ( Honor 8A, camera 13 Mp )

**Comment by saghul** [comment]
Can you paste the full logcat? IIRC the supported resolutions are logged.

**Comment by kaleemlab** [comment]
Fatal Exception: java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
       at android.graphics.SurfaceTexture.nativeUpdateTexImage(SurfaceTexture.java)
       at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:249)
       at org.webrtc.SurfaceTextureHelper.updateTexImage(SurfaceTextureHelper.java:334)
       at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:354)
       at org.webrtc.SurfaceTextureHelper.lambda$new$0$org-webrtc-SurfaceTextureHelper(SurfaceTextureHelper.java:207)
       at org.webrtc.SurfaceTextureHelper$$ExternalSyntheticLambda5.onFrameAvailable(:2)
       at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:212)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.os.HandlerThread.run(HandlerThread.java:67)
