### ISSUE TITLE
Android crash when execute call(peerId, strem) function

### ISSUE THREAD

**Issue by xueling794** [react-native-webrtc/react-native-webrtc#1605]
react-native-webrtc [124.0.3][118.0.7]
rn-peer [1.0.0]
peerjs[1.5.4] Only in Web
1. mediaDevices.getUserMedia({
    audio: true,
    video: {facingMode: 'user'},
  })  render RTCView is ok.
2. peer.call('user1', mediaStream).then(res => console.log(res))
      .catch(e => console.error(e)); App is crashed. 
3. Use Web peerjs call React-native app with mediaStream. rn-peer answer media stream and render remote stream is ok. Web and App is all ok.
4. I trace in Android Studio I get the log:
```
2024-08-06 10:05:34.835 28233-28233 libc                    com.rn_demo                          E  Access denied finding property "vendor.vivo.stylus.enabe"
2024-08-06 10:05:35.178 28233-28341 com.oney.W...bRTCModule com.rn_demo                          D  getUserMedia(audio): {}
2024-08-06 10:05:35.202 28233-28341 com.oney.W...bRTCModule com.rn_demo                          D  MediaStream id: 706e8923-cdea-4491-b27c-22b983864a29
2024-08-06 10:05:35.214 28233-28319 ReactNativeJS           com.rn_demo                          I  { _tracks: 
                                                                                                       [ { label: '',
                                                                                                           _constraints: {},
                                                                                                           _enabled: true,
                                                                                                           _settings: {},
                                                                                                           _muted: false,
                                                                                                           _peerConnectionId: undefined,
                                                                                                           _readyState: 'live',
                                                                                                           id: 'f02a9cb2-d251-4b37-96aa-f4237f3a3df3',
                                                                                                           kind: 'audio',
                                                                                                           remote: false } ],
                                                                                                      _id: '706e8923-cdea-4491-b27c-22b983864a29',
                                                                                                      _reactTag: '706e8923-cdea-4491-b27c-22b983864a29' }
2024-08-06 10:05:35.287 28233-28319 ReactNativeJS           com.rn_demo                          I  'init peer', [Function: call]
2024-08-06 10:05:35.306 28233-28260 OpenGLRenderer          com.rn_demo                          I  Slow UI.
2024-08-06 10:05:35.311 28233-28260 OpenGLRenderer          com.rn_demo                          I  Slow UI.
2024-08-06 10:05:35.314 28233-28319 ReactNativeJS           com.rn_demo                          I  rn-webrtc:pc:DEBUG 1 ctor +16s
2024-08-06 10:05:35.319 28233-28319 ReactNativeJS           com.rn_demo                          I  rn-webrtc:pc:DEBUG 1 addTrack +5ms
2024-08-06 10:05:35.320 28233-28233 com.rn_demo             com.rn_demo                          E  No package ID ff found for ID 0xffffffff.
2024-08-06 10:05:35.331 28233-28233 com.oney.W...bRTCModule com.rn_demo                          W  No video stream for react tag: 706e8923-cdea-4491-b27c-22b983864a29
2024-08-06 10:05:35.331 28233-28233 org.webrtc.Logging      com.rn_demo                          I  EglRenderer: setMirrorHorizontally: true
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.lang.String)' on a null object reference
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at org.webrtc.JniHelper.getStringBytes(JniHelper.java:25)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at org.webrtc.PeerConnection.nativeCreateDataChannel(Native Method)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at org.webrtc.PeerConnection.createDataChannel(PeerConnection.java:865)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at com.oney.WebRTCModule.PeerConnectionObserver.createDataChannel(PeerConnectionObserver.java:167)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at com.oney.WebRTCModule.WebRTCModule.lambda$createDataChannel$36(WebRTCModule.java:1368)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at com.oney.WebRTCModule.WebRTCModule.$r8$lambda$JO36YPT1V19SFxkLi-744clgBOw(Unknown Source:0)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at com.oney.WebRTCModule.WebRTCModule$$ExternalSyntheticLambda25.call(Unknown Source:8)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2024-08-06 10:05:35.336 28233-28341 System.err              com.rn_demo                          W  	at java.lang.Thread.run(Thread.java:923)
2024-08-06 10:05:35.336 28233-28341 rtc                     com.rn_demo                          E  #
                                                                                                    # Fatal error in: gen/jni_headers/sdk/android/generated_metrics_jni/../../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 95
                                                                                                    # last system error: 0
                                                                                                    # Check failed: !env->ExceptionCheck()
                                                                                                    # 
2024-08-06 10:05:35.337 28233-28341 libc                    com.rn_demo                          A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 28341 (pool-6-thread-1), pid 28233 (com.rn_demo)
2024-08-06 10:05:35.523 28233-28233 InputTransport          com.rn_demo                          I  Destroy ARC handle: 0xb40000734aae7940
2024-08-06 10:05:35.533 28373-28373 DEBUG                   pid-28373                            A  pid: 28233, tid: 28341, name: pool-6-thread-1  >>> com.rn_demo <<<
2024-08-06 10:05:35.536 28373-28373 DEBUG                   pid-28373                            A        #01 pc 0000000000417f10  /data/app/~~1_ZclwsMRL2ihvtbavtH0Q==/com.rn_demo-AzsikY7WyFiNRom-f5pA-w==/base.apk!libjingle_peerconnection_so.so (offset 0x2875000) (BuildId: 4bbf0f3487b96085)
2024-08-06 10:05:36.695 28399-28399 com.rn_demo             pid-28399                            I  Late-enabling -Xcheck:jni
2024-08-06 10:05:36.729 28399-28399 com.rn_demo             pid-28399                            I  Unquickening 25 vdex files!
2024-08-06 10:05:36.824 28399-28399 NetworkSecurityConfig   com.rn_demo                          D  No Network Security Config specified, using platform default
2024-08-06 10:05:36.826 28399-28399 NetworkSecurityConfig   com.rn_demo                          D  No Network Security Config specified, using platform default
2024-08-06 10:05:36.860 28399-28399 libc                    com.rn_demo                          E  Access denied finding property "ro.vendor.perf.scroll_opt.heavy_app"
2024-08-06 10:05:36.875 28399-28399 SoLoader                com.rn_demo                          V  Init System Loader delegate

```
5. ReactNative launch  packager command line last log when crash by call
```
 LOG  rn-webrtc:pc:DEBUG 1 ctor +16s
 LOG  rn-webrtc:pc:DEBUG 1 addTrack +5ms
```

**Comment by saghul** [comment]
Interesting. I wonder if null is used as the datachannel label. Can you check if that's the case?

**Comment by saghul** [comment]
![Screenshot 2024-08-06 at 15 24 25](https://github.com/user-attachments/assets/540867c3-9ee9-4675-bd3d-cc07318a904d)

Browsers have some interesting behavior. We can emulate it indeed..
