### ISSUE TITLE
[BUG] Error npm install on master branch with package.json

### ISSUE THREAD

**Issue by us4r93t3mnus** [react-native-webrtc/react-native-webrtc#1624]
#### Observed Behavior:
```
react-native-webrtc % npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

> react-native-webrtc@124.0.4 prepare
> husky install && bob build

husky - Git hooks installed
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 38 files in src with babel
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 38 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
node_modules/@types/react/index.d.ts:44:53 - error TS2307: Cannot find module 'scheduler/tracing' or its corresponding type declarations.

44 import { Interaction as SchedulerInteraction } from 'scheduler/tracing';
                                                       ~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@types/react/index.d.ts:44

✖ Failed to build definition files.
bob build

build files for publishing

Opciones:
  --help     Muestra ayuda                                            [booleano]
  --version  Muestra número de versión                                [booleano]

Error: Failed to build definition files.
    at build (/Users/user/Desktop/repositorios/react-native-webrtc/node_modules/react-native-builder-bob/lib/targets/typescript.js:112:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.handler (/Users/user/Desktop/repositorios/react-native-webrtc/node_modules/react-native-builder-bob/lib/index.js:379:9)
npm error code 1
npm error path /Users/user/Desktop/repositorios/react-native-webrtc
npm error command failed
npm error command sh -c husky install && bob build
npm error A complete log of this run can be found in: /Users/user/.npm/_logs/2024-09-16T11_31_26_833Z-debug-0.log
```

#### Steps to reproduce the issue:
1- git clone from master
2- delete package-lock.json
3- npm install 
4- wait to fail

If you don't remove package-lock.json it works perfect. Maybe some broken dependencies?

**Comment by davidliu** [comment]
That sounds working as intended? Deleting the package-lock.json isn't something that should be done.
