### ISSUE TITLE
On Android 14, the app crashes during screen sharing, although it works fine on lower versions

### ISSUE THREAD

**Issue by Awais7899** [react-native-webrtc/react-native-webrtc#1639]
#### Expected Behavior:
Screensharing should be working on all devices.

#### Observed Behavior:
Screensharing crashes on android 14.
#### Steps to reproduce the issue:
Explain how the issue can be reproduced.

#### Platform Information  
* **React Native Version**:  0.75.4
* **WebRTC Module Version**: 124.0.4
* **Platform OS + Version**: android 14

**Comment by saghul** [comment]
Can you please share the crash logs? Did you enable the foreground service as per the docs? https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#screen-sharing

**Comment by Awais7899** [comment]
> Can you please share the crash logs? Did you enable the foreground service as per the docs? https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#screen-sharing

Yes, It's working up to Android 13, there is no error just the App stops working, and crashes.

**Comment by saghul** [comment]
If the app crashes there must be a crash backtrace. Check with `adb logcat`.

**Comment by Awais7899** [comment]
10-30 12:57:10.997 17698 17698 E AndroidRuntime: java.lang.RuntimeException: Unable to start service app.notifee.core.ForegroundService@6221b86 with Intent { act=app.notifee.core.ForegroundService.START cmp=com.videocalllatest/app.notifee.core.ForegroundService (has extras) }: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{52b5582 17698:com.videocalllatest/u0a240} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media]
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5019)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2396)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:243)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:338)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8446)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1064)
10-30 12:57:10.997 17698 17698 E AndroidRuntime: Caused by: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{52b5582 17698:com.videocalllatest/u0a240} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media]
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:3067)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:3051)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:3034)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2976)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7464)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.Service.startForeground(Service.java:862)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at app.notifee.core.ForegroundService.onStartCommand(SourceFile:21)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5001)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        ... 9 more
10-30 12:57:10.997 17698 17698 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at [com.android.server.am](http://com.android.server.am/).ActiveServices.validateForegroundServiceType(ActiveServices.java:2717)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at [com.android.server.am](http://com.android.server.am/).ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2419)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at [com.android.server.am](http://com.android.server.am/).ActiveServices.setServiceForegroundLocked(ActiveServices.java:1765)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at [com.android.server.am](http://com.android.server.am/).ActivityManagerService.setServiceForeground(ActivityManagerService.java:14337)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:        at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:13061)
10-30 12:57:10.997 17698 17698 E AndroidRuntime:
10-30 12:57:11.008  1271 28428 E Metadata2/Entry: itemAt(531):Get data error , tag ffffffff, mContentPtr 0x0 (itemAt){#531:vendor/mediatek/proprietary/hardware/mtkcam/utils/metadata/metadata/Entry.cpp}
10-30 12:57:11.042  1271 28069 E Metadata2/Entry: itemAt(531):Get data error , tag ffffffff, mContentPtr 0x0 (itemAt){#531:vendor/mediatek/proprietary/hardware/mtkcam/utils/metadata/metadata/Entry.cpp}
10-30 12:57:11.046   946   946 E SurfaceFlinger: MtkDuration override mode is disabled
10-30 12:57:11.110  1271  3261 E HalIspImp: [setP1Params] No ISP Profile: CaptureIntent: 1, Default Profile: 0 (setP1Params){#682:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_6s/isp_hal/HalIspImp.cpp}
10-30 12:57:11.144  1271  3261 E HalIspImp: [setP1Params] No ISP Profile: CaptureIntent: 1, Default Profile: 0 (setP1Params){#682:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_6s/isp_hal/HalIspImp.cpp}
10-30 12:57:11.147  1191  3265 E Camera3-OutputStream: getBufferLockedCommon: Stream 0: Can't dequeue next output buffer: Broken pipe (-32)
10-30 12:57:11.148  1191  3293 E Surface : queueBuffer: error queuing buffer, -32
10-30 12:57:11.152  1191  3293 E Surface : queueBuffer: error queuing buffer, -32
10-30 12:57:11.160  1191  3293 E Surface : queueBuffer: error queuing buffer, -32
10-30 12:57:11.168  1271 30629 E MtkCam/HalSensor: [sendCommand] [sendCommand] error: SENSOR_CMD_SET_SWITCH_TG_FOR_STAGGER 16448
10-30 12:57:11.168  1271 30629 E MtkCam/HalSensor:  (sendCommand){#2960:vendor/mediatek/proprietary/hardware/mtkcam/drv/src/sensor/mt6789/../common/v1_1/HalSensor.cpp}
10-30 12:57:11.171  1191  3293 E Surface : queueBuffer: error queuing buffer, -32
10-30 12:57:11.180  1271  3332 E aao_buf_mgr: [dequeueHwBuf] m_pSttPipe AAO deque fail, skip m_pSttPipe AAHO deque
10-30 12:57:11.180  1271  3332 E aao_buf_mgr:  (dequeueHwBuf){#347:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_6s/buf_mgr/AAOBufMgr.cpp}
10-30 12:57:11.180  1271  3332 E aao_buf_mgr: [dequeueHwBuf] m_pSttPipe deque success, but AAOsize is 0
10-30 12:57:11.180  1271  3332 E aao_buf_mgr:  (dequeueHwBuf){#359:vendor/mediatek/proprietary/hardware/mtkcam/aaa/source/isp_6s/buf_mgr/AAOBufMgr.cpp}
10-30 12:57:11.200  1686  2093 E  Aurora_Exception :  exception PolicyManager=getUserPreloadPolicy fail,userList is null
10-30 12:57:11.209   946  1005 E BufferQueueDebug: [ZeroScreen#2938](this:0xb4000072d85a40b0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'ZeroScreen#2938'
10-30 12:57:11.212   946   946 E BufferQueueDebug: [ZeroScreen#2938 (Mirror)#2939](this:0xb4000072d85901c0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'ZeroScreen#2938 (Mirror)#2939'
10-30 12:57:11.243   946  1005 E BufferQueueDebug: [com.transsion.XOSLauncher/com.android.quickstep.src.com.android.launcher3.uioverrides.QuickstepLauncher#2940](this:0xb4000072d8598a70,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'com.transsion.XOSLauncher/com.android.quickstep.src.com.android.launcher3.uioverrides.QuickstepLauncher#2940'
10-30 12:57:11.245 20850 20933 E OpenGLRenderer: Unable to match the desired swap behavior.
10-30 12:57:11.246   946   946 E BufferQueueDebug: [com.transsion.XOSLauncher/com.android.quickstep.src.com.android.launcher3.uioverrides.QuickstepLauncher#2940 (Mirror)#2941](this:0xb4000072d857c2d0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'com.transsion.XOSLauncher/com.android.quickstep.src.com.android.launcher3.uioverrides.QuickstepLauncher#2940 (Mirror)#2941'
10-30 12:57:11.254   946  3089 E BufferQueueDebug: [Surface(name=6db4b15 NavigationBar0)/@0x6f94950 - animation-leash of insets_animation#2942](this:0xb4000072d84fc080,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Surface(name=6db4b15 NavigationBar0)/@0x6f94950 - animation-leash of insets_animation#2942'
10-30 12:57:11.259   946   946 E BufferQueueDebug: [Surface(name=6db4b15 NavigationBar0)/@0x6f94950 - animation-leash of insets_animation#2942 (Mirror)#2943](this:0xb4000072d85683e0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Surface(name=6db4b15 NavigationBar0)/@0x6f94950 - animation-leash of insets_animation#2942 (Mirror)#2943'
10-30 12:57:11.263   946  1004 E BufferQueueDebug: [Surface(name=de0829d StatusBar)/@0x5ac749 - animation-leash of insets_animation#2944](this:0xb4000072d85cec20,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Surface(name=de0829d StatusBar)/@0x5ac749 - animation-leash of insets_animation#2944'
10-30 12:57:11.270   946  1009 E surfaceflinger: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
10-30 12:57:11.272   946   946 E BufferQueueDebug: [Surface(name=de0829d StatusBar)/@0x5ac749 - animation-leash of insets_animation#2944 (Mirror)#2945](this:0xb4000072d85a6e40,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Surface(name=de0829d StatusBar)/@0x5ac749 - animation-leash of insets_animation#2944 (Mirror)#2945'
10-30 12:57:11.319  1191  1483 E CameraService: binderDied: Java client's binder died, removing it from the list of active clients
10-30 12:57:11.321  2134  2564 E OpenGLRenderer: Unable to match the desired swap behavior.
10-30 12:57:11.334   946  1009 E surfaceflinger: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
10-30 12:57:11.334  1686  5071 E AppOps  : Operation not started: uid=10240 pkg=com.videocalllatest(null) op=RECORD_AUDIO
10-30 12:57:11.367   946  3089 E BufferQueueDebug: [Transition Root: Task=1#2946](this:0xb4000072d84cb9f0,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Transition Root: Task=1#2946'
10-30 12:57:11.370   946   946 E BufferQueueDebug: [Transition Root: Task=1#2946 (Mirror)#2947](this:0xb4000072d837e720,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Transition Root: Task=1#2946 (Mirror)#2947'
10-30 12:57:11.382   905   940 E mtkpower@impl: [setMode] unknown type
10-30 12:57:11.388   946   946 E BufferQueueDebug: [Screenshot Parent#2948](this:0xb4000072d83f8e50,id:-1,api:0,p:-1,c:-1) id info cannot be read from 'Screenshot Parent#2948'
10-30 12:57:11.391   946  1009 E surfaceflinger: == MALI DEBUG ===eglp_winsys_populate_image_templates ==12288
10-30 12:57:11.400  2350  2616 E BtGatt.ContextMap: Context not found for ID 0
10-30 12:57:11.402   946  1004 E BufferQueueDebug: [1f2a90a ActivityRecordInputSink com.transsion.XOSLauncher/com.android.quickstep.src.com.android.launcher3.uioverrides.QuickstepLauncher#2949](this:0xb4000072d83f8e50,id:-1,api:0,p:-1,c:-1) id info cannot be read from '1f2a90a ActivityRecordInputSink com.transsion.XOSLauncher/com.android.quickstep.src.com.android.launcher3.uioverrides.QuickstepLauncher#2949'
10-30 12:57:11.414   946   946 E BufferQueueDebug: [1f2a90a ActivityRecordInputSink com.transsion.XOSLauncher/com.android.quickstep.src.com.android.launcher3.uioverrides.QuickstepLauncher#2949 (Mirror)#2950](this:0xb4000072d859b800,id:-1,api:0,p:-1,c:-1) id info cannot be read from '1f2a90a ActivityRecordInputSink com.transs

> If the app crashes there must be a crash backtrace. Check with `adb logcat`.

**Comment by saghul** [comment]
```
  <service
    android:name="app.notifee.core.ForegroundService"
  android:foregroundServiceType="mediaProjection" 
  tools:replace="android:foregroundServiceType" />
```

Not sure this is right. That is not our foreground service, but the one from notifee. I see our docs are a bit confusing / wrong...

Please follow this: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#screen-sharing

To use the builtin MP service, that should work.

**Comment by Awais7899** [comment]
> ```
>   <service
>     android:name="app.notifee.core.ForegroundService"
>   android:foregroundServiceType="mediaProjection" 
>   tools:replace="android:foregroundServiceType" />
> ```
> 
> Not sure this is right. That is not our foreground service, but the one from notifee. I see our docs are a bit confusing / wrong...
> 
> Please follow this: https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#screen-sharing
> 
> To use the builtin MP service, that should work.

https://github.com/invertase/notifee/pull/1050#issue-2357401592

I followed these instructions and performed some changes in the AndroidManifest.xml , now it's working fine.
