### ISSUE TITLE
RTCView doesn't render video stream in android emulator

### ISSUE THREAD

**Issue by RooneyJung** [react-native-webrtc/react-native-webrtc#313]
getting local stream using MediaStreamTrack and getUserMedia and set stream object like this...

MediaStreamTrack.getSources(infos => {
     .... some codes...
    getUserMedia({
        ... some options...
    }, function (stream) {
       // set state
       this.setState({ localStream: stream });
    }, function(e) {
    });
}

the render code ...

render() {
  if (this.state.localStream) {
     return (
       <RTCView
           streamURL={this.state.localStream.toURL()}
           style={{
              backgroundColor: 'red',
           }}
       />
    );
  } else {
     return (<View></View>);
  }
}

In iOS devices, there are not any problems.
But in android emulator, it does not render video stream.
In my case, I set background-color 'red'. so, just rendered 'red' box.
And remote stream also has same problem.

The plugin 1.58.0 has a issue #292, so I clone and use master branch today.

Few month ago, I had made a app with RN 0.44 and plugin version 1.57.0.
It has not any problems in iOS and android.

* **React Native version**: 0.45.1
* **Plugin version**: master branch
* **OS**:  Android 7.1.1 (API 25) - emulator
* **OS version**:

**Comment by zxcpoiu** [comment]
emulator has it's own limitations and not recommended in this libs.
please test on real devices. 

btw, you can use coding block ( triple backtick ) to quote your snippet

**Comment by saghul** [comment]
Did you enable the camera emulator? The Android emulator does not emulate a camera by default.

**Comment by jjdp** [comment]
it even crashes on geny now

**Comment by saghul** [comment]
Any logs / backtrace?

**Comment by jjdp** [comment]
gave me this:

```
07-19 04:30:42.067 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.067 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.068 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.068 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.221 I/com.oney.WebRTCModule.WebRTCModule( 2913): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]

07-19 04:30:42.222 I/com.oney.WebRTCModule.WebRTCModule( 2913): getUserMedia(video): { NativeMap: {"facingMode":"user","optional":[{"sourceId":"1"}],"mandatory":{"minFrameRate":30,"minHeight":1280,"minWidth":720}} }

07-19 04:30:42.222 I/CameraManagerGlobal( 2913): Connecting to camera service

07-19 04:30:42.223 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.223 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.223 I/CameraService(  413): getCameraCharacteristics: Switching to HAL1 shim implementation...

07-19 04:30:42.223 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.223 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.223 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.223 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.223 I/CameraService(  413): getCameraCharacteristics: Switching to HAL1 shim implementation...

07-19 04:30:42.223 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.223 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.224 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.224 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.224 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.224 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.226 D/com.oney.WebRTCModule.WebRTCModule( 2913): Creating video capturer using Camera1 API.

07-19 04:30:42.226 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.226 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.226 I/org.webrtc.Logging( 2913): Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90

07-19 04:30:42.227 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.227 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.227 I/org.webrtc.Logging( 2913): Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 90

07-19 04:30:42.227 I/org.webrtc.Logging( 2913): Camera1Enumerator: getCameraIndex: Camera 0, Facing back, Orientation 90

07-19 04:30:42.227 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.227 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.228 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.228 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.228 I/org.webrtc.Logging( 2913): Camera1Enumerator: getCameraIndex: Camera 1, Facing front, Orientation 90

07-19 04:30:42.228 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.228 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.228 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.228 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.229 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.229 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.229 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.229 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.229 I/org.webrtc.Logging( 2913): Camera1Enumerator: Index: 0. Camera 0, Facing back, Orientation 90

07-19 04:30:42.230 V/EmulatedCamera_Camera(  413): getCameraInfo

07-19 04:30:42.230 V/EmulatedCamera_BaseCamera(  413): getCameraInfo

07-19 04:30:42.230 I/org.webrtc.Logging( 2913): Camera1Enumerator: Index: 1. Camera 1, Facing front, Orientation 90

07-19 04:30:42.230 D/com.oney.WebRTCModule.WebRTCModule( 2913): Create front camera Camera 1, Facing front, Orientation 90 succeeded

07-19 04:30:42.231 I/org.webrtc.Logging( 2913): EglBase14: SDK version: 23. isEGL14Supported: true

07-19 04:30:42.231 D/        ( 2913): HostConnection::get() New Host Connection established 0xd2e52ae0, tid 3011

07-19 04:30:42.233 E/EGL_emulation( 2913): rcCreateContext returned 0

07-19 04:30:42.233 E/EGL_emulation( 2913): tid 3011: eglCreateContext(874): error 0x3003 (EGL_BAD_ALLOC)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): SurfaceTextureHelper: Camera SurfaceTextureHelper create failure

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.EglBase14.createEglContext(EglBase14.java:260)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.EglBase14.<init>(EglBase14.java:58)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.EglBase.create(EglBase.java:86)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:114)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:36)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:69)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:65)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at org.webrtc.ThreadUtils$4.run(ThreadUtils.java:182)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at android.os.Handler.handleCallback(Handler.java:739)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at android.os.Handler.dispatchMessage(Handler.java:95)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at android.os.Looper.loop(Looper.java:148)

07-19 04:30:42.233 E/org.webrtc.Logging( 2913): 	at android.os.HandlerThread.run(HandlerThread.java:61)

07-19 04:30:42.233 I/org.webrtc.Logging( 2913): CameraCapturer: startCapture: 720x1280@30

07-19 04:30:42.233 D/AndroidRuntime( 2913): Shutting down VM

07-19 04:30:42.233 E/AndroidRuntime( 2913): FATAL EXCEPTION: main

07-19 04:30:42.233 E/AndroidRuntime( 2913): Process: com.sclubber.debug, PID: 2913

07-19 04:30:42.233 E/AndroidRuntime( 2913): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object reference

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at org.webrtc.CameraCapturer.createSessionInternal(CameraCapturer.java:286)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at org.webrtc.CameraCapturer.startCapture(CameraCapturer.java:280)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at org.webrtc.Camera1Capturer.startCapture(Camera1Capturer.java:19)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.oney.WebRTCModule.GetUserMediaImpl.getUserVideo(GetUserMediaImpl.java:405)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.oney.WebRTCModule.GetUserMediaImpl.getUserMedia(GetUserMediaImpl.java:294)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.oney.WebRTCModule.GetUserMediaImpl.access$000(GetUserMediaImpl.java:28)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.oney.WebRTCModule.GetUserMediaImpl$1.invoke(GetUserMediaImpl.java:257)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.oney.WebRTCModule.GetUserMediaImpl$3.invoke(GetUserMediaImpl.java:456)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.oney.WebRTCModule.PermissionUtils$2.onReceiveResult(PermissionUtils.java:189)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at android.os.Handler.handleCallback(Handler.java:739)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at android.os.Handler.dispatchMessage(Handler.java:95)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at android.os.Looper.loop(Looper.java:148)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at android.app.ActivityThread.main(ActivityThread.java:5417)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at java.lang.reflect.Method.invoke(Native Method)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

07-19 04:30:42.233 E/AndroidRuntime( 2913): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by saghul** [comment]
> 07-19 04:30:42.233 E/EGL_emulation( 2913): tid 3011: eglCreateContext(874): error 0x3003 (EGL_BAD_ALLOC)

There seems to be some problem with the EGL emulation, maybe? 🤷‍♂️

**Comment by jjdp** [comment]
maybe geny specific, ill test on android studio emulator tomorrow

**Comment by jjdp** [comment]
same on android studio emu. gives the same egl context error

**Comment by pewh** [comment]
+1 any workaround please?

**Comment by arunrajarao** [comment]
I have exactly the same issue even on physical device ....
Zorder doesn't help. its just plain blank white screen

**Comment by saghul** [comment]
I'm going to close this. The view does work in both physical devices and emulators.

If you see a black screen it means most likely ICE was not successfully established.

**Comment by kunalpgithub** [comment]
I am still having issue, what worke for you?
