### ISSUE TITLE
[Android][1.69.0] Crash when close connection

### ISSUE THREAD

**Issue by trananhkhoi46** [react-native-webrtc/react-native-webrtc#591]
#### Expected behavior
It should not crash

#### Observerd behavior
The app is crashed when I close a Component

#### Steps to reproduce the problem
1. Navigate to a component which is calling to another user
2. Press back button on Android phone to close that component (then I expect the connection will be terminated automatically)
3. The app is crashed

#### Platform information
Android

#### Workaround
I am not sure if that workaround is working. Because the issue does not always happen. I hope that can be fixed soon.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/20500433/52991329-d785d600-343e-11e9-94de-31d4c62e660b.png">

#### Log from Android Native
FATAL EXCEPTION: pool-16-thread-1
                                                   Process: com.chattingapp.day2, PID: 22844
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
                                                       at org.webrtc.VideoTrack.removeSink(VideoTrack.java:47)
                                                       at com.oney.WebRTCModule.VideoTrackAdapter.removeAdapter(VideoTrackAdapter.java:57)
                                                       at com.oney.WebRTCModule.PeerConnectionObserver.close(PeerConnectionObserver.java:127)
                                                       at com.oney.WebRTCModule.WebRTCModule.peerConnectionCloseAsync(WebRTCModule.java:895)
                                                       at com.oney.WebRTCModule.WebRTCModule.lambda$peerConnectionClose$16(WebRTCModule.java:887)
                                                       at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$mPS_N0abbNQnEl2DvAxjIn1Q6ak.run(lambda)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:762)
02-19 11:36:55.935 3209-11332/? E/CameraDeviceClient: Disconnect from CameraDeviceClient
02-19 11:36:56.209 22844-25332/? E/libEGL: call to OpenGL ES API with no current context (logged once per thread)
02-19 11:36:56.254 22844-22844/? E/WindowManager: android.view.WindowLeaked: Activity com.chattingapp.day2.MainActivity has leaked window DecorView@86d4d82[MainActivity] that was originally added here
                                                      at android.view.ViewRootImpl.<init>(ViewRootImpl.java:572)
                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:97)
                                                      at android.app.Dialog.show(Dialog.java:419)
                                                      at com.facebook.react.views.modal.ReactModalHostView.showOrUpdate(ReactModalHostView.java:257)
                                                      at me.listenzz.modal.TranslucentModalHostView.showOrUpdate(TranslucentModalHostView.java:26)
                                                      at com.facebook.react.views.modal.ReactModalHostManager.onAfterUpdateTransaction(ReactModalHostManager.java:103)
                                                      at com.facebook.react.views.modal.ReactModalHostManager.onAfterUpdateTransaction(ReactModalHostManager.java:24)
                                                      at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:33)
                                                      at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:269)
                                                      at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
                                                      at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:888)
                                                      at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1001)
                                                      at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:46)
                                                      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1061)
                                                      at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                                                      at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
                                                      at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                      at android.view.Choreographer.doFrame(Choreographer.java:635)
                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                      at android.os.Looper.loop(Looper.java:154)
                                                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by 8BallBomBom** [comment]
If you are changing to another call screen and also wanting the other call to close.
How are you going about closing the connection?
