### ISSUE TITLE
Android Application Crashes On Boot: Application Has Stopped

### ISSUE THREAD

**Issue by mronline** [react-native-webrtc/react-native-webrtc#845]
#### Observerd behavior

`E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.sampleapp, PID: 4986
    java.lang.NoSuchMethodError: No static method createEgl14([I)Lorg/webrtc/EglBase14; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.sampleapp-2/base.apk)
        at com.oney.WebRTCModule.EglUtils.getRootEglBase(EglUtils.java:35)
        at com.oney.WebRTCModule.EglUtils.getRootEglBaseContext(EglUtils.java:62)
        at com.oney.WebRTCModule.WebRTCModule.initAsync(WebRTCModule.java:98)
        at com.oney.WebRTCModule.WebRTCModule.lambda$new$0$WebRTCModule(WebRTCModule.java:73)
        at com.oney.WebRTCModule.-$$Lambda$WebRTCModule$CnyHZvkjDxq52UReGHUZlY0JsVw.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)`

#### Steps to reproduce the problem

In setup:
- I just did first step.
- I think other step will be automatically (react-native-auto-link).

#### Platform information

* **React Native version**: 0.63.2
* **Plugin version**: ^1.75.3
* **OS**:  Android
* **OS version**: 4+

**Comment by arunrajarao** [comment]
I HAD THE SAME ISSUE , MAKE SURE MINSDK IS 24 OR HIGHER AND IT ILL WORK
