### ISSUE TITLE
Turn the camera on and off 30 times will cause the app to crash

### ISSUE THREAD

**Issue by hpcplus2** [react-native-webrtc/react-native-webrtc#924]
Turn the camera on and off 30 times will cause the app to crash!
Error message: **Failed to create EGL context: 0x3003**
Using the official [demo](https://github.com/react-native-webrtc/react-native-webrtc/tree/master/examples/GumTestApp) will also reproduce the problem

#### Expected behavior
don't crash app

#### Observerd behavior
![image](https://user-images.githubusercontent.com/11487560/103126180-76795a00-46c8-11eb-9699-0566c238e388.png)

#### Steps to reproduce the problem
* Start the app
* Click Start and wait for the camera to turn on
* Click Stop and wait for the camera to turn off
* Repeat this procedure around 30 times
* App crash

#### Platform information

* **React Native version**: 0.63.3
* **Plugin version**: 1.84.1
* **OS**: Android
* **OS version**: 10

**Comment by saghul** [comment]
@tmoldovan8x8 This might be a good way to test the EGL renderers issue.

**Comment by loganathansellappa** [comment]
Are there any updates on this issue? The issue happens in the latest version too. 
Its mainly associated with localstream, which we get from navigator.mediadevices.getUserMedia. Stopping the track and releasing the localstream doesnt clear/remove the eglcontext.


```
localStream.getTracks().forEach((t) => t.stop())
localStream.release()
```

**Comment by saghul** [comment]
The context is related to the view, not the track. I have no updates, sorry.

**Comment by fizawisedv** [comment]
@saghul I have removed the RTCView from the UI component, so it is not rendered now. I am only receiving the media stream, but still turning the camera on and off 30 times causes the same issue.

**Comment by minh-nguyen-tma** [comment]
Hi @saghul ,
This issue happens in function WebRTCView.tryAddRendererToVideoTrack.
I have the stack trace here:
`E/org.webrtc.Logging: com.oney.WebRTCModule.WebRTCModule: java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:282)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase.create(EglBase.java:158)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:241)
        at org.webrtc.-$$Lambda$EglRenderer$miQc1-F9Qqw0EkFhtMh5sNQ-7uU.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at org.webrtc.EglRenderer.init(EglRenderer.java:232)
        at org.webrtc.EglRenderer.init(EglRenderer.java:259)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at com.oney.WebRTCModule.WebRTCView.tryAddRendererToVideoTrack(WebRTCView.java:541)
        at com.oney.WebRTCModule.WebRTCView.onAttachedToWindow(WebRTCView.java:203)
        at android.view.View.dispatchAttachedToWindow(View.java:18351)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5077)
        at android.view.ViewGroup.addView(ViewGroup.java:4865)
        at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:459)
        at android.view.ViewGroup.addView(ViewGroup.java:4805)
        at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:38)
        at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:534)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:914)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
        at android.view.Choreographer.doCallbacks(Choreographer.java:823)
        at android.view.Choreographer.doFrame(Choreographer.java:755)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:998)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003`
Because the Android accepts 30 times to create EGL context only. So this issue happens.
I see in EglUtils class, we are using EglBase shared instance, but each time we call getEglBaseContext(), we will get a new context object.
Can you please take a look at it?
Thanks.
